### ISSUE TITLE
Unrecognised token in template 

### ISSUE THREAD

**Issue by Potokin** [inex-solutions/configgen#10]
Doesn't seem to be any support for this package anymore, but it's worth a shot, because I am at a loss here.
The package works like it is supposed to, only having 1 problem: the token in the template doesn't get recognized and just gets deleted every time I try to change it using a command in the .csproj file.

Can post the full files if there is still any support out there.

**Comment by roblevine** [comment]
Hi,

I only have limited time for support these days, but more than happy to have a look. Yes, please post some files that illustrate the problem.

Thanks

**Comment by Potokin** [comment]
While writing the whole explanation for my problem, I stumbled upon the culprit!
When calling the command, I was using the old 1.0.9 branch, not the 2.0.24-beta branch.
v1.0.9 still seems to have this issue, but seeing that this version is 8 years old, I don't think it matters.

Thanks for the fast answer! Amazing to see a package being supported after all these years!

**Comment by roblevine** [comment]
Thanks for letting me know :)
