### ISSUE TITLE
ExitCode = Success if errors found during generation

### ISSUE THREAD

**Issue by aprice30** [inex-solutions/configgen#4]
If a generation of a template causes errors the result is written out to screen but ExitCode = Success is set by default.

It would be nice if we could return an error code so the generator can be used in systems like Teamcity to show errors.

**Comment by roblevine** [comment]
Hi aprice30,

This is what the -e or --errors-on-warnings option should do, but it looks like I haven't finished implementing it (I could have sworn I had, but I've taken a bit of a break from ConfigGen recently).

I'll fix this up forthwith, so you can use this feature to fail a build.

Thanks,

**Comment by roblevine** [comment]
Hi,

I've just uploaded a new NuGet package to fix this issue: v2.0.16-beta

Apologies for the delay.

Also - I realised this is probably you Adam - is that right? 

Please let me know if this does not rectify your issue,

Thanks,

Rob

**Comment by aprice30** [comment]
Hi Rob, yes it's me. I think someone is just applying your change to our code base so will let you know. Sorry for the long delay. Thank you for the change.

Adam
